import streamlit as st
from model_helper import predict
import time

# Page configuration
st.set_page_config(
    page_title="Vehicle Damage Detector",
    page_icon="🚗",
    layout="wide"
)

# Custom CSS for better styling
st.markdown("""
    <style>
    .main {
        padding: 2rem;
    }
    .stTitle {
        color: #1f77b4;
        font-size: 3rem !important;
        font-weight: 700;
        text-align: center;
        margin-bottom: 0.5rem;
    }
    .subtitle {
        text-align: center;
        color: #666;
        font-size: 1.2rem;
        margin-bottom: 2rem;
    }
    .upload-section {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 15px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .result-box {
        background: #f8f9fa;
        padding: 1.5rem;
        border-radius: 10px;
        border-left: 4px solid #1f77b4;
        margin-top: 1rem;
    }
    .result-title {
        font-size: 1.3rem;
        font-weight: 600;
        color: #333;
        margin-bottom: 0.5rem;
    }
    .result-value {
        font-size: 1.8rem;
        font-weight: 700;
        color: #1f77b4;
    }
    </style>
""", unsafe_allow_html=True)

# Header
st.title("🚗 Vehicle Damage Detector")
st.markdown('<p class="subtitle">Upload an image to detect vehicle damage instantly</p>', unsafe_allow_html=True)

# Create two columns for better layout
col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.markdown("### 📤 Upload Image")
    uploaded_file = st.file_uploader(
        "Choose a vehicle image",
        type=['png', 'jpeg', 'jpg'],
        help="Supported formats: PNG, JPEG, JPG"
    )

    if uploaded_file:
        st.image(uploaded_file, caption='Uploaded Image', use_container_width=True)
    else:
        # Placeholder when no image is uploaded
        st.info("👆 Please upload an image to get started")
        st.markdown("""
        **Tips for best results:**
        - Use clear, well-lit images
        - Ensure the damage area is visible
        - Avoid blurry or distant shots
        """)

with col2:
    st.markdown("### 🔍 Detection Results")

    if uploaded_file:
        # Save and process the image
        img_path = 'temp_file.jpeg'
        with open(img_path, 'wb') as f:
            f.write(uploaded_file.getbuffer())

        # Show progress
        with st.spinner('🔄 Analyzing image...'):
            time.sleep(0.5)  # Brief pause for better UX
            prediction = predict(img_path)

        # Display results in a styled box
        st.markdown(f"""
        <div class="result-box">
            <div class="result-title">Prediction:</div>
            <div class="result-value">{prediction}</div>
        </div>
        """, unsafe_allow_html=True)

        # Success message
        st.success("✅ Analysis complete!")

        # Additional actions
        st.markdown("---")

        # Prepare detailed report for download
        from datetime import datetime

        report = f"""
╔══════════════════════════════════════════════════════════╗
║         VEHICLE DAMAGE DETECTION REPORT                  ║
╚══════════════════════════════════════════════════════════╝

Analysis Date & Time: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Image File: {uploaded_file.name}
File Size: {uploaded_file.size / 1024:.2f} KB

─────────────────────────────────────────────────────────

DETECTION RESULT:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Predicted Class: {prediction}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

─────────────────────────────────────────────────────────
⚠️ Disclaimer:
• This prediction is generated by an AI model and should be considered as a reference only.  
• Model accuracy is approximately ~80%, so results may vary.  
• For any queries or detailed information, please contact SHUBHAM at samop20799@gmail.com.  

─────────────────────────────────────────────  

Generated by Vehicle Damage Detector AI  
Developed by SHUBHAM | Powered by Deep Learning Technology.

"""

        st.download_button(
            label="📥 Download Detailed Report",
            data=report,
            file_name=f"damage_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            use_container_width=True
        )

        # Print to console
        print(f"Prediction: {prediction}")
    else:
        st.info("Upload an image in the left panel to see results here")

# Footer
st.markdown("---")
st.markdown(
    '<p style="text-align: center; color: #666;">Made by SHUBHAM • Fast & Accurate Detection</p>',
    unsafe_allow_html=True
)